DM: 
  Nacts: 468
  max_stroke_in_m: 5e-6

WFS:
  apex_angle: 0.0003906262449032515
  oversampling: 4
  modulationAngleInLambdaOverD: 3.0
  lambdaInM: 1000e-9

DETECTOR:
  detector_shape: [256, 256]
  RON: 1.0
  quantum_efficiency: 0.7
  beam_splitter_ratio: 0.5  # fraction of light to WFS

SLOPE.COMPUTER:
  loopFrequencyInHz: 1500
  integratorGain: 0.2
  delay: 2                  # loop delay in steps
  nModes2Correct: 467
  ttOffloadFrequencyInHz: 0 # if 0, no TT offloading

TELESCOPE:
  pupilSizeInM: 1.8
  pupilSizeinPixels: 128
  throughput: 0.11          # accounting for beam splitter

ATMO:
  r0: [12e-2, 10e-2, 10e-2] # [m]
  outerScaleInM: 25
  windSpeed: [4, 6, 10]     # [m/s]
  windAngle: [-120, 45, 0]  # [deg] CCW from East

LOOP:
  nIterations: 3000
  starMagnitude: 3.0
