DM1: 
  Nacts: 468
  max_stroke_in_m: 5e-6   # Not yet used

PYR1:
  oversampling: 5
  lambdaInM: 1000e-9            # [m] sensor wavelength
  bandWidthInM: 0e-9            # [m] sensor band amplitude
  subapPixSize: 31.5            # subaperture diameter in pix
  subapPixSep: 32               # pixel distance between subaps

CCD1:
  detector_shape: [160,160]     # detector pixel size
  RON: 1.0                      # readout noise in e-
  quantum_efficiency: 0.7       # detector quantum efficiency
  beam_splitter_ratio: 0.5      # fraction of light to WFS

SLOPE.COMPUTER1:
  loopFrequencyInHz: 1000     
  integratorGain: 0.5         # loop integrator gain
  delay: 2                    # loop delay in steps
  nModes2Correct: 467         # number of reconstructor modes
  ttOffloadFrequencyInHz: 0   # if 0, no TT offloading
  modulationInLambdaOverD: 3.0  # modulation amplitude

DM2: 
  Nacts: 241
  max_stroke_in_m: 40e-6   # Not yet used

PYR2:
  oversampling: 4
  lambdaInM: 750e-9             # [m] sensor wavelength
  bandWidthInM: 0e-9            # [m] sensor band amplitude
  subapPixSize: 19.5            # subaperture diameter in pix
  subapPixSep: 24               # pixel distance between subaps

CCD2:
  detector_shape: [80,80]       # detector pixel size
  RON: 1.0                      # readout noise in e-
  quantum_efficiency: 0.7       # detector quantum efficiency
  beam_splitter_ratio: 0.5      # fraction of light to WFS

SLOPE.COMPUTER2:
  loopFrequencyInHz: 4000     
  integratorGain: 0.5         # loop integrator gain
  delay: 2                    # loop delay in steps
  nModes2Correct: 240         # number of reconstructor modes
  ttOffloadFrequencyInHz: 0   # if 0, no TT offloading
  modulationInLambdaOverD: 0.0  # modulation amplitude


TELESCOPE:
  pupilSizeInM: 1.8         # [m] telescope diameter
  pupilSizeInPixels: 160    # pixels across the pupil diameter
  throughput: 0.11          # accounting for beam splitter

ATMO:
  outerScaleInM: 25         # [m]
  r0: [12e-2, 10e-2, 10e-2] # [m]
  windSpeed: [4, 6, 10]     # [m/s]
  windAngle: [-120, 45, 0]  # [deg] CCW from East

LOOP:
  nIterations: 200
  starMagnitude: 0.0
  simFreqHz: 4000          # simulation frequency in Hz
