DM: 
  Nacts: 468
  max_stroke_in_m: 5e-6   

PYR:
  oversampling: 4           # oversampling for PSF computation
  lambdaInM: 1000e-9        # [m] sensor wavelength
  bandWidthInM: 0e-9        # [m] sensor band amplitude
  subapPixSize: 39.5        # subaperture diameter in pix
  subapPixSep: 10           # pixel distance between subaps

CCD:
  detector_shape: [160,160]    # detector pixel size
  RON: 1.0                      # readout noise in e-
  quantum_efficiency: 0.7       # detector quantum efficiency
  beam_splitter_ratio: 0.5      # fraction of light to WFS

SLOPE.COMPUTER:
  loopFrequencyInHz: 1500     
  integratorGain: 0.6           # loop integrator gain
  delay: 2                      # loop delay in steps
  nModes2Correct: 467           # number of reconstructor modes
  ttOffloadFrequencyInHz: 0     # TBI
  modulationInLambdaOverD: 3.0

TELESCOPE:
  pupilSizeInM: 1.8         # [m] telescope diameter
  centerObscuration: 0.0    # [m] central obscuration diameter
  pupilSizeInPixels: 160    # pixels across the pupil diameter
  throughput: 0.11          # accounting for beam splitter

ATMO:
  outerScaleInM: 25         # [m]
  r0: [10e-2,12e-2,15e-2]   # [m]
  windSpeed: [5,8,10]       # [m/s]
  windAngle: [0,45,-60]     # [deg] CCW from East

LOOP:
  nIterations: 300
  starMagnitude: 6.0
  simFreqHz: 1500          # simulation frequency in Hz
  recompute: False         # if False, any calibration data saved from 
                           # previous runs is loaded rather than recomputed
