DM.out: 
  Nacts: 468
  mmax_stroke_in_m: 5e-6  

PYR.out:
  oversampling: 4 #5
  lambdaInM: 1000e-9            # [m] sensor wavelength
  bandWidthInM: 0e-9            # [m] sensor band amplitude
  subapPixSize: 39.5            # subaperture diameter in pix
  subapPixSep: 8                # pixel distance between subaps

CCD.out:
  detector_shape: [160,160]     # detector pixel size
  RON: 1.0                      # readout noise in e-
  quantum_efficiency: 0.7       # detector quantum efficiency
  beam_splitter_ratio: 0.5      # fraction of light to WFS

SLOPE.COMPUTER.out:
  loopFrequencyInHz: 1000     
  integratorGain: 0.4           # loop integrator gain
  delay: 5                      # loop delay in steps
  nModes2Correct: 468           # number of reconstructor modes
  ttOffloadFrequencyInHz: 0     # if 0, no TT offloading
  modulationInLambdaOverD: 3.0  # modulation amplitude

DM.in: 
  Nacts: 241
  max_stroke_in_m: 40e-6   

PYR.in:
  oversampling: 4
  lambdaInM: 800e-9             # [m] sensor wavelength
  bandWidthInM: 0e-9            # [m] sensor band amplitude
  subapPixSize: 39.5            # subaperture diameter in pix
  subapPixSep: 20               # pixel distance between subaps

CCD.in:
  detector_shape: [160,160]       # detector pixel size
  RON: 1.0                      # readout noise in e-
  quantum_efficiency: 0.7       # detector quantum efficiency
  beam_splitter_ratio: 0.5      # fraction of light to WFS

SLOPE.COMPUTER.in:
  loopFrequencyInHz: 4000     
  integratorGain: 0.2           # loop integrator gain
  delay: 2                      # loop delay in steps
  nModes2Correct: 240           # number of reconstructor modes
  ttOffloadFrequencyInHz: 0     # if 0, no TT offloading
  modulationInLambdaOverD: 1.0  # modulation amplitude


TELESCOPE:
  pupilSizeInM: 1.8         # [m] telescope diameter
  pupilSizeInPixels: 160    # pixels across the pupil diameter
  throughput: 0.11          # accounting for beam splitter

ATMO:
  outerScaleInM: 25         # [m]
  r0: [12e-2, 10e-2, 10e-2] # [m]
  windSpeed: [4, 6, 10]     # [m/s]
  windAngle: [-120, 45, 0]  # [deg] CCW from East

LOOP:
  nIterations: 400
  starMagnitude: 0.0
  simFreqHz: 4000          # simulation frequency in Hz
  recompute: False         # if False, any calibration data saved from 
                           # previous runs is loaded rather than recomputed
