DM1: 
  Nacts: 468
  mmax_stroke_in_m: 5e-6  

PYR1:
  oversampling: 4 #5
  lambdaInM: 750e-9            # [m] sensor wavelength
  bandWidthInM: 0e-9            # [m] sensor band amplitude
  subapPixSize: 35.5            # subaperture diameter in pix
  subapPixSep: 8                # pixel distance between subaps

CCD1:
  detector_shape: [144,144]     # detector pixel size
  RON: 0.3                      # readout noise in e-
  quantum_efficiency: 0.9       # detector quantum efficiency
  beam_splitter_ratio: 0.5      # fraction of light to WFS

SLOPE.COMPUTER1:
  loopFrequencyInHz: 1000     
  integratorGain: 0.9          # loop integrator gain
  delay: 8                    # loop delay in steps
  nModes2Correct: 415         # number of reconstructor modes
  ttOffloadFrequencyInHz: 0   # if 0, no TT offloading
  modulationInLambdaOverD: 3.0  # modulation amplitude

DM2: 
  Nacts: 192
  max_stroke_in_m: 5e-6

PYR2:
  oversampling: 4
  lambdaInM: 1200e-9             # [m] sensor wavelength
  bandWidthInM: 0e-9            # [m] sensor band amplitude
  subapPixSize: 23.5            # subaperture diameter in pix
  subapPixSep: 8               # pixel distance between subaps

CCD2:
  detector_shape: [96,96]       # detector pixel size
  RON: 0.3                      # readout noise in e-
  quantum_efficiency: 0.9       # detector quantum efficiency
  beam_splitter_ratio: 0.5      # fraction of light to WFS

SLOPE.COMPUTER2:
  loopFrequencyInHz: 4000     
  integratorGain: 0.2         # loop integrator gain
  delay: 2                    # loop delay in steps
  nModes2Correct: 175         # number of reconstructor modes
  ttOffloadFrequencyInHz: 0   # if 0, no TT offloading
  modulationInLambdaOverD: 1.0  # modulation amplitude


TELESCOPE:
  pupilSizeInM: 1.8         # [m] telescope diameter
  centerObscuration: 0.6    # [m] central obscuration diameter
  pupilSizeInPixels: 128    # pixels across the pupil diameter
  throughput: 0.11          # accounting for beam splitter

ATMO:
  outerScaleInM: 25         # [m]
  r0: [8e-2, 6e-2, 12e-2, 10e-2, 10e-2] # [m]
  windSpeed: [6, 6, 8, 8, 10]     # [m/s]
  windAngle: [-120, 30, 45, 65, 0]  # [deg] CCW from East
  recompute: False

LOOP:
  nIterations: 1000
  starMagnitude: 1.0
  simFreqHz: 4000          # simulation frequency in Hz
  recompute: False         # if False, any calibration data saved from 
                           # previous runs is loaded rather than recomputed
